version: '3'

services:


  redis:
    image: redis:4.0.5-alpine
    ports: 
      - '6379:6379'

  landing_page:
    build: ./
    depends_on:
      - 'redis'
    links: 
      - redis
    environment: 
      REDIS_URL: 'redis://0.0.0.0:6379'
    ports: 
      - '80:3004'